baseURL = "njcustomoutfitters.netlify.app"
languageCode = "en-us"
title = "NJCustomOutfitters"
themesDir = "./themes"
theme = "hugo-hero-theme"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"